name: "Run HTC Mock"
description: "Action running an HTC Mock session from a Kubernetes Job"
inputs:
  armonik-core-version:
    description: "Version of ArmoniK.Core to use"
    required: true
  ntasks:
    description: "Number of tasks to be created"
    default: "100"
    required: false
  subtasks-levels:
    description: "Levels of subtasking"
    default: "1"
    required: false
  grpc-client-endpoint:
    description: "External IP address of ArmoniK's API"
    required: true
  working-directory:
    description: "Working directory (should be the ArmoniK repo root folder)"
    required: false
    default: ${{ github.workspace }}
  session-name:
    description: "A name that is provided as the value for key 'SessionName' for the 'HtcMock__Options' option"
    required: false
    default: "cicd"
  purge-data:
    description: "Whether to purge session after execution"
    required: false
    default: "false"
outputs:
  session-name:
    description: "Name of the HTC Mock session to help retrieve its id"
    value: ${{ steps.run.outputs.session-name }}
runs:
  using: composite
  steps:
    - id: run
      name: HTC Mock Client running
      working-directory: ${{ inputs.working-directory }}
      shell: bash
      env:
        ARMONIK_CORE_VERSION: ${{ inputs.armonik-core-version }}
        NTASKS: ${{ inputs.ntasks }}
        SUBTASKS_LEVELS: ${{ inputs.subtasks-levels }}
        SESSION_NAME: ${{ inputs.session-name }}
        GRPC_CLIENT_ENDPOINT: ${{ inputs.grpc-client-endpoint }}
        PURGE_DATA: ${{ inputs.purge-data }}
      run: |
        set -ex
        cd tools/ci
        echo "session-name=$SESSION_NAME" >> "$GITHUB_OUTPUT"
        sed "s/@@ARMONIK_CORE_VERSION@@/$ARMONIK_CORE_VERSION/g; s/@@NTASKS@@/$NTASKS/g; s/@@SUBTASKS_LEVELS@@/$SUBTASKS_LEVELS/g; s/@@SESSION_NAME@@/$SESSION_NAME/g; s/@@GRPC_CLIENT_ENDPOINT@@/$GRPC_CLIENT_ENDPOINT/g; s/@@PURGE_DATA@@/$PURGE_DATA/g" \
          tools/ci/htcmock-job-template.yml | 
          kubectl apply -f -
